name: Build Tweak
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl perl git rsync libssl-dev
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # SDK indirme (iOS 14.5)
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mkdir -p ~/theos/sdks
          mv sdks-master/*.sdk ~/theos/sdks/
          rm -rf master.zip sdks-master

      - name: Build Package
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          # Rootless ve Final sürüm olarak derle
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1
        
      - name: Upload Deb Package
        uses: actions/upload-artifact@v3
        with:
          name: AR-Hile-DEB-Dosyasi
          path: packages/*.deb

      - name: Upload Dylib (Sideload Icin)
        uses: actions/upload-artifact@v3
        with:
          name: AR-Hile-Ham-Dosyalar
          path: .theos/obj/debug/*.dylib
